version: "3.8"

services:
  pwa-node:
    image: node:latest
    user: node
    working_dir: /home/node/app
    networks:
      - pwa3322
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: >
      sh -c "rm -rf node_modules &&
             npm install &&
             npm run dev"
    restart: always
    stdin_open: true
    tty: true
networks:
  pwa3322:
